2021-03-11 17:07:06.7842 INFO Metodo ObtenerProgramaAuditoria llamdo con parametro 0
2021-03-11 17:07:14.9290 ERROR An error occurred while updating the entries. See the inner exception for details. inner -> Unknown column 'CodigoServicio_ws' in 'field list' inner -> Unknown column 'CodigoServicio_ws' in 'field list' stactrace ->    at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 49
2021-03-11 17:07:14.9450 ERROR An error occurred while updating the entries. See the inner exception for details. inner -> Unknown column 'CodigoServicio_ws' in 'field list' inner -> Unknown column 'CodigoServicio_ws' in 'field list' stactrace ->    at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 49
